services:
    php-cli:
        build:
            context: ./docker/dev
            dockerfile: php-cli.docker
        container_name: php-cli
        restart: unless-stopped
        networks:
            - backend
        env_file:
            - ./app/.env.local
        volumes:
            - ./app:/app
        working_dir: /app
        tty: true

    postgres:
        image: postgres:alpine
        container_name: postgres
        restart: unless-stopped
        networks:
            - backend
        env_file:
            - ./app/.env.local
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/tmp:/postgresData
        ports:
            - '5432:5432'

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
            - backend
        env_file:
            - ./app/.env.local
        volumes:
            - ./redis/data:/data
            - ./docker/dev/redis/redis.conf:/usr/local/etc/redis/redis.conf


networks:
    backend:
