doctrine:
    dbal:
        connections:
            docker:
                host: '%env(POSTGRES_HOST_SOCKET)%'
                user: '%env(POSTGRES_USER)%'
                password: '%env(POSTGRES_PASSWORD)%'
                dbname: '%env(POSTGRES_DB)%'
                driver: 'pdo_pgsql'
        default_connection: docker

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
