framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    http_client:
        scoped_clients:
            telegram.http.client:
                base_uri: 'https://api.telegram.org/bot%env(TELEGRAM_BOT_API_TOKEN)%/'
                timeout: '%env(float:TELEGRAM_BOT_API_TIMEOUT_SECONDS)%'
                headers:
                    Accept: application/json

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
